#!/bin/bash

filename="$HOME/Pictures/screenshot_`date +%Y-%m-%d_%T`.png"
case "$1" in 
	full)
		import -window root "$filename"
		;;
	crop)
		import "$filename"
		;;
	window)
		import -border -window `xwininfo | awk '/.*Window id:.*/ {print $4}'` "$filename"	
		;;
	*)
		echo "Usage: $0 [full|window|crop]"
		exit 2
esac
notify-send -i camera-photo-symbolic.symbolic "Screenshot" "Saved to $filename"
exit 0
